### ISSUE TITLE
Add all documentation to Wiki

### ISSUE THREAD

**Issue by danielandastro** [danielandastro/SCAPP_Base#1]
Add all the intro stuff into relevant wiki pages

**Comment by OnesQuared** [comment]
I'm assuming you are trying to move all the docs into wiki? I'd take this issue if its available, although not sure how to edit the wiki, since pull request doesn't do wikis

**Comment by danielandastro** [comment]
> I'm assuming you are trying to move all the docs into wiki? I'd take this issue if its available, although not sure how to edit the wiki, since pull request doesn't do wikis

Small thing i didnt consider, anyway it is done now

**Comment by danielandastro** [comment]
> I'm assuming you are trying to move all the docs into wiki? I'd take this issue if its available, although not sure how to edit the wiki, since pull request doesn't do wikis

I would have given you push access

If you are interested in joining my small project, let me know
